### ISSUE TITLE
If requested temporal range is larger than data range - then give back original files - requires alignment to be truncated into range

### ISSUE THREAD

**Issue by agstephens** [roocs/rook#100]
This is relevant to this code:

https://github.com/roocs/rook/blob/master/rook/director/alignment.py#L14-L30

The code needs to:
1. Get requested time range
2. Get full time range of dataset (i.e. all files)
3. If requested time range exceed full time range:
  - Return all original files as the aligned request.

**Comment by agstephens** [comment]
Should be fixed in: https://github.com/roocs/rook/commit/63b9f25c354a341fb02d1b2013b39f9972d641ed

@ellesmith88 please merge into your "resolve_urls" branch.

**Comment by JamesVarndell** [comment]
Hi @agstephens, @ellesmith88 and @cehbrecht,

Does rooki know how to handle the 'original files' response? Earlier this week I was able to pass a temporal subset that was larger than the data, but I now get a "Sorry, process failed" error from rooki (version 0.3.0). I ran the following experiments:
- Temporal subset much larger than the data range (failed)
- Temporal subset that exactly matches the data range (failed)
- Temporal subset very slightly smaller than the data range (succeeded)

Let me know if you'd like more information.

Many thanks!
James

**Comment by agstephens** [comment]
@JamesVarndell I think rooki should simply represent the original files as those available from URLs on the data node. In my tests, I get files back from each response (so the server is working).

This works for me:

http://rook-wps1.ceda.ac.uk/wps?service=WPS&version=1.0.0&request=Execute&identifier=subset&status=true&storeExecuteResponse=true&DataInputs=collection=c3s-cmip6.ScenarioMIP.INM.INM-CM5-0.ssp245.r1i1p1f1.Amon.rlds.gr1.v20190619;time=1900-01-01/2500-12-30

Do you get a valid response from it?

**Comment by agstephens** [comment]
Implemented here:

https://github.com/roocs/rook/blob/master/rook/director/alignment.py
