### ISSUE TITLE
Note on production roll-out failure: 2021-01-29

### ISSUE THREAD

**Issue by agstephens** [roocs/rook#106]
Production service was failing because:

1. `/tmp/inventory_cache` was not updating to reflect new inventories.
2. the ansible playbook installed a basic demo `roocs.ini` file at: `/etc/roocs.ini` - now disabled.

This is relevant on **all servers**.

**Comment by cehbrecht** [comment]
We can avoid the overwrite of our manually changed `roocs.ini`:
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html#parameter-force

**Comment by agstephens** [comment]
Fixed in ansible playbooks.
