### ISSUE TITLE
Processes missing from provenance

### ISSUE THREAD

**Issue by JamesVarndell** [roocs/rook#110]
It looks like level and area subsetting information is currently missing from the provenance documents returned from rooki. Here's an example workflow with an area subset and the returned provenance PNG:

```
{
    "inputs": {
        "hurs": ["c3s-cmip6.ScenarioMIP.CCCma.CanESM5.ssp126.r1i1p1f1.Amon.hurs.gn.v20190429"]
    },
    "steps": {
        "subset_hurs_1": {"run": "subset", "in": {"collection": "inputs/hurs", "area": "10,40,30,60"}}
    },
    "outputs": {"output": "subset_hurs_1/output"},
    "doc": "workflow"
}
```

![provenance](https://user-images.githubusercontent.com/36902610/106637049-34bab980-657a-11eb-985c-7785baa084dd.png)

**Comment by JamesVarndell** [comment]
Also of note is the inclusion of `apply_fixes: True` - based on our discussion earlier today I was under the impression that fixes would _not_ be applied?

**Comment by agstephens** [comment]
Thanks @JamesVarndell we'll take a look.

**Comment by agstephens** [comment]
@cehbrecht @ellesmith88: It looks like there are 3 places in `rook` where `apply_fixes` might need to be addressed in relation to workflows:

1. We explicitly set it on stages of a workflow, here:

https://github.com/roocs/rook/blob/dd01dab1235d04fe925d641e5877d7a49d271ce7/rook/workflow.py#L34

- I think that is to say - _only apply fixes on the first stage_

2. When we instance a subclass of `Operator`, we _could_ send it `apply_fixes`:

https://github.com/roocs/rook/blob/dd01dab1235d04fe925d641e5877d7a
49d271ce7/rook/workflow.py#L71

3. It is an argument to the constructor of the Operator classes (such as `Subset` and `Average`):

https://github.com/roocs/rook/blob/dd01dab1235d04fe925d641e5877d7a49d271ce7/rook/operator.py#L16

My initial thoughts are:
 - we can switch it off in the base Operator constructor, i.e. set it as `apply_fixes=False`
 - then it will only be used if the first stage of a workflow has asked for it, e.g. `{"apply_fixes": True}`

**Comment by cehbrecht** [comment]
@agstephens As a quick fix we can set `apply_fixes` to `False` ... in the Operator and Workflow. 

Currently the `apply_fixes=True` is hard-coded in the workflow for the first step. It should be set by the workflow description with `False` as default. 

I will prepare a patch ... also for the missing `area` parameter.

**Comment by cehbrecht** [comment]
@JamesVarndell the quick fix (disable `apply_fixes`) is on the production service. The fix for the missing parameters like `area` is on the test service:
![fixed prov](http://cp4cds-cn2.cloud.dkrz.de:80/outputs/rook/04db012e-6706-11eb-9ba8-fa163ec710d3/provenance.png)

The `startedAtTime` and `endedAtTime` are also updated to see the duration of the process.
