### ISSUE TITLE
Provenance does only documents one NetCDF file when multiple files are generated

### ISSUE THREAD

**Issue by agstephens** [roocs/rook#113]
## Description

Provenance does only documents one NetCDF file when multiple files are generated.

We need a unit test or two that generates multiple output files and asserts that they are all recorded in the provenance JSON output.

@cehbrecht: We could overwrite the following in ROOCS_CONFIG to change the splitting rule (to split over smaller files):

https://github.com/roocs/clisops/blob/master/clisops/etc/roocs.ini#L4-L5

```
[clisops:write]
file_size_limit = 1GB
```

**Comment by cehbrecht** [comment]
Fixed by #114. 

Deployed on demo service (use larger time extend):
https://nbviewer.jupyter.org/github/roocs/rooki/blob/master/notebooks/demo/demo-rooki-subset-by-time.ipynb
