### ISSUE TITLE
Provide documentation about the provenance process

### ISSUE THREAD

**Issue by agstephens** [roocs/rook#118]
@cehbrecht: ECMWF has requested that we provide documentation about the provenance JSON and PNG files that are included in the WPS responses. 

The required information is how they are generated – specifically:
- The software library used to create the files;
- A short summary of how to interpret the provenance information.

Where do you think we should provide this documentation? Maybe a special `README-provenance.md` at the top-level of the `rook` repo.

**Comment by cehbrecht** [comment]
@agstephens I can add a section to the rook docs:
https://rook-wps.readthedocs.io/en/latest/

**Comment by agstephens** [comment]
@cehbrecht good plan. Thanks

**Comment by cehbrecht** [comment]
The provenancs section is on ReadTheDocs:
https://rook-wps.readthedocs.io/en/latest/prov.html
