### ISSUE TITLE
Release a version of rook which includes average

### ISSUE THREAD

**Issue by ellesmith88** [roocs/rook#130]
Average has been included in the latest `clisops` release (v0.6.1), the latest `daops` release (v0.5.0) and any changes needed are included in the latest `roocs-utils` release (v0.2.1) but it hasn't been released for `rook` yet. 

Could we release a version of rook that includes the working `wps_average` process so that we can tell ECMWF that average is ready.

**Comment by ellesmith88** [comment]
@cehbrecht Are you able to do this please? 😄

**Comment by cehbrecht** [comment]
> @cehbrecht Are you able to do this please? 😄

yes :smile:

can we merge the smoke tests PR #131? So, I would have same already in place ... we can improve them later.

**Comment by ellesmith88** [comment]
@cehbrecht yes they look really good, I will merge

**Comment by cehbrecht** [comment]
Release 0.4.0 is done and deployed on the test-server rook1.

Smoke tests pass:
```
/var/lib/pywps/smoke.sh rook
```
