### ISSUE TITLE
Use intake catalog server for file lookups

### ISSUE THREAD

**Issue by cehbrecht** [roocs/rook#133]
## Description

The lookups on filesystem to select files for a dataset are quite slow.

We can use intake server to speed this up:
https://intake.readthedocs.io/en/latest/tools.html#intake-server

As fall-back we can still have the current filesystem-lookup.

## Environment

* rook version used, if any:
* Python version, if any:
* Operating System:

## Steps to Reproduce

```
Paste the command(s) you ran and the output.
```

**Comment by agstephens** [comment]
@cehbrecht can you elaborate on the types of file-system look-up that are taking a long time?

**Comment by cehbrecht** [comment]
When using `CMIP6` it will look up and select files on the filesystem. It could use the ESGF-search to select the requested files.

**Comment by cehbrecht** [comment]
The `search` query from the `intake-server` does not do what I hoped ... it just searches the catalog list ... but it does not run a search on the catalog itself. So a search like `search(time="2001/2010")` does not work.

**Comment by cehbrecht** [comment]
For our own catalogs `c3s-cmip6` etc ... we could convert them to `intake` catalogs (at least for internal use, dataset/files loopups). `intake` loads the catalog also into memory on each request. As long they are small, we will survive :) But we could load these catalogs in a database (mongodb?, key-value store?) which we can query ... and maybe later use a `stac` or `ogcapi-features` search interface, maybe using [pygeoapi](https://pygeoapi.io/).

**Comment by agstephens** [comment]
@cehbrecht can we close this now?

**Comment by cehbrecht** [comment]
@agstephens yes ... we use the postgres db as workaround. Need a better solution ... but later.
