### ISSUE TITLE
average operator and usage of original files?

### ISSUE THREAD

**Issue by cehbrecht** [roocs/rook#135]
## Description

In release 0.4.0 there is a quick fix:
https://github.com/roocs/rook/blob/06f255ec49138086c59f732646cd8c1e304bfad1/rook/director/director.py#L85

When using the average operator we don't return original files. Right?

## Environment

* rook version used, if any:
* Python version, if any:
* Operating System:

## Steps to Reproduce

```
Paste the command(s) you ran and the output.
```

## Additional Information

#130

**Comment by ellesmith88** [comment]
@cehbrecht You're right, that's a good spot - I made my average tests using `cmip5` datasets so I need to add some with with `c3s-cmip6` datatsets. I think this is fine as a fix?

**Comment by ellesmith88** [comment]
In the case where `dims=None`, `average_over_dims` returns the dataset as it is, so in this case would we want to return the original files or would we always expect an input?

**Comment by cehbrecht** [comment]
> In the case where `dims=None`, `average_over_dims` in `clisops` returns the dataset as it is, so in this case would we want to return the original files or would we always expect an input?

I think `average` without an argument makes no sense. We already have the `subset` operator for this (returning original files only). We can have it as a required argument in WPS/rook. rook would raise an exception when missing.

**Comment by ellesmith88** [comment]
sounds sensible!

**Comment by agstephens** [comment]
I agree that the `original_files` argument should not even be exposed for the `average` Operator, and that we can make it mandatory to provide at least one dimension in the `dims` argument.

**Comment by agstephens** [comment]
@ellesmith88 I think we had this discussion but I can't see that we are enforcing that `dims` cannot be sent in as an empty string/value. If that was the case it would default to `None` (I think). 

Can you test whether `rook` is allowing an empty value for `dims`. If so, please add a check in the process code to raise an Exception in such a case. Thanks
