### ISSUE TITLE
Requests hanging indefinitely

### ISSUE THREAD

**Issue by JamesVarndell** [roocs/rook#140]
When making requests for different experiments under the same model, I noticed that some requests were fairly fast (~1 minute) whereas others (for the same volume of data) were very slow, and perhaps hanging indefinitely (still running after multiple hours).

For example, a request for MIROC6 monthly near-surface temperature under experiment SSP1-1.9 (for the whole temporal period and whole globe) took 1 minute to complete successfully - whereas an identical request for SSP2-4.5 has been running for hours with no response.

**Comment by JamesVarndell** [comment]
@cehbrecht it turns out I was mistakenly making these requests directly to the CEDA endpoint - but switching to the load-balanced endpoint seems to yield the exact same reponse.

**Comment by cehbrecht** [comment]
@JamesVarndell 
I think I have found a fix:
https://github.com/roocs/rook/issues/139

Should work now on the load-balanced node (dkrz only). 

The default for the output file size need to be updated. 

But still need to work on the error response ...

**Comment by agstephens** [comment]
@JamesVarndell @cehbrecht I have been looking at the jobs running on the CEDA service. **They were all still running!**
I have rebooted the server just in case something was stuck. I'm going to get a colleague to do some digging into why those processes were running so slowly.

**Comment by cehbrecht** [comment]
@JamesVarndell I'm collecting notebooks for the test cases:
https://nbviewer.jupyter.org/github/roocs/rooki/tree/master/notebooks/tests/

For example this one relates to this issue:
https://nbviewer.jupyter.org/github/roocs/rooki/blob/master/notebooks/tests/test-c3s-cmip6-subset-hadgem-ssp245.ipynb

By default the use the test server (notebooks can be run on binder) ... but you can change the rook url.

**Comment by agstephens** [comment]
@JamesVarndell @cehbrecht:

I have run some more tests on the production servers. When I replicate a query that took hours on Friday I can make it run in a few minutes when the output files are being written to the local disk.

I am repeating my tests when writing to the shared drive that the production system writes to normally.

**Comment by agstephens** [comment]
@JamesVarndell @cehbrecht @ellesmith88:

I think I've found the culprit. Here are the issues:

1. write outputs directly to the large shared disk (JASMIN Group Workspace) - which does not support _parallel-writes_ --> duration > 2 hours
2. write outputs to special shared disk - which **does** support _parallel-writes_ --> duration < 5 minutes
3. write outputs to special shared disk **and** then move them to large shared disk --> duration < 10 minutes

So I think we have a solution, I will put a patch together for `clisops` - but I'll roll it out in advance in production.

**Comment by cehbrecht** [comment]
@agstephens smoke passed  ... except for this one:

**Comment by agstephens** [comment]
Thanks @cehbrecht, can you please re-run that smoke test that failed, and let me know the result.

**Comment by cehbrecht** [comment]
@agstephens still the same result:

**Comment by agstephens** [comment]
Closing this one. We'll move the smoke test discussion elsewhere.
