### ISSUE TITLE
Need to override the intake use of $HOME directory

### ISSUE THREAD

**Issue by agstephens** [roocs/rook#167]
## Description

When using `intake`, we need to be able to override where the library uses the `$HOME` directory - which is _not_ accessible on JASMIN service.

## Environment

* rook version used, if any: `intake` branch
* Python version, if any: py3.7
* Operating System: centos7

## Steps to Reproduce

I have done some experimenting but I still get the service trying to write to `$HOME` for intake content.

I dumped the intake cache to a file, and got this:

```
{'auth': {'cls': 'intake.auth.base.BaseAuth'}, 'port': 5000, 'cache_dir': '/tmp/intake_cache', 'cache_disabled': False, 'cache_download_progress': True, 'logging': 'INFO', 'catalog_path': [], 'persist_path': '/tmp/intake_persist'}
```

But it still seems to fail with: `Process error: Errno 13 Permission denied: /home/c4cds`

@cehbrecht please can you take a look in more detail. Thanks

**Comment by cehbrecht** [comment]
The intake code tells us more than the docs:
https://github.com/intake/intake/blob/master/intake/config.py

We need to set the environment variable `INTAKE_CONF_DIR` to avoid the use of `$HOME`.
