### ISSUE TITLE
Add a CWL workflow example

### ISSUE THREAD

**Issue by cehbrecht** [roocs/rook#3]
## Description

See:
https://github.com/common-workflow-language/python-cwlgen

## Environment

* roocs wps demo version used, if any:
* Python version, if any:
* Operating System:

**Comment by cehbrecht** [comment]
First try with a simple json wf inspired by CWL:
https://github.com/roocs/roocs-wps-demo/blob/master/tests/testdata/subset-wf.json

Example usage with orchestrate process:
https://github.com/roocs/roocs-wps-demo/blob/master/notebooks/roocs-demo.ipynb

**Comment by agstephens** [comment]
We should have a detailed discussion with our Canadian friends on the benefits of using _compliant_ CWL.

**Comment by cehbrecht** [comment]
An option could be to use our simplified workflow description and map it to CWL workflow. One could use the CWL implemention to run the workflow. 

But currently we don't have a CWL that works with daops. Should daops library be called on the command line?

**Comment by agstephens** [comment]
@cehbrecht - regarding your last point. It would be nice to have a daops command-line option but I think we should aim to add it later in the project - when the API has been fully developed and stabilised.

**Comment by agstephens** [comment]
Done
