### ISSUE TITLE
Remove mini-esgf-data 

### ISSUE THREAD

**Issue by ellesmith88** [roocs/rook#43]
## Description

mini-esgf-data was added directly. This has been changed to a submodule however the data needs to be removed

**Comment by cehbrecht** [comment]
The handling of the git submodule is somehow troublesome. Also we have this issue on Windows:
https://github.com/roocs/clisops/pull/48

Maybe we can skip using git submodule and pytest would fetch the test-data on init? It could also use a tagged version  (or specific commit) of the test-data. The test-data itself will then be ignored by the rook, clisops etc repo.

**Comment by Zeitsperre** [comment]
That's a good idea. Given that the data is only needed for the testing of the library, ensuring that this test data doesn't come along with the functional code when installing it in other places would be good. I know that part of the issue for https://github.com/roocs/clisops/pull/48 is that pip installing a cloned git repo with a submodule causes the Windows version of pip to complain.

Given that this test data repo is being used on multiple projects, would the solution you mention work for all of them?

**Comment by cehbrecht** [comment]
@Zeitsperre We might like to have a pytest extension to provide the test data (download/update from git). Currently all projects expect the mini-esgf-data at the same place.

**Comment by Zeitsperre** [comment]
@cehbrecht We recently implemented a new means of providing access to our own xclim-testdata repository via a slightly modified `xarray.tutorial.open_dataset()`. The relevant PR is https://github.com/Ouranosinc/xclim/pull/571.

I think this would solve the problem, allowing us not to have to load the repo as a submodule, and as an added bonus, it seems to work in both posix and Windows systems!

**Comment by cehbrecht** [comment]
> @cehbrecht We recently implemented a new means of providing access to our own xclim-testdata repository via a slightly modified `xarray.tutorial.open_dataset()`. The relevant PR is [Ouranosinc/xclim#571](https://github.com/Ouranosinc/xclim/pull/571).
> 
> I think this would solve the problem, allowing us not to have to load the repo as a submodule, and as an added bonus, it seems to work in both posix and Windows systems!

@Zeitsperre Sounds good :) I will have a look at it.

**Comment by agstephens** [comment]
Now removed.
