### ISSUE TITLE
Add a cron task to clean out old job outputs from output directories

### ISSUE THREAD

**Issue by agstephens** [roocs/rook#56]
E.g.:

```
# Tidy up old files in output directories
30 4 * * * find DIR -maxdepth 1 -type f -mtime +60 -exec rm -f {} \;
```

Maybe also add a second rule to remove empty directories.
And maybe just allow the user the configure the number of days before old content is deleted.

**Comment by cehbrecht** [comment]
latest ansible playbook has now a task to clean wps outputs and temp files via cronjob:
https://github.com/bird-house/ansible-wps-playbook/blob/master/roles/pywps/tasks/cronjob.yml
