### ISSUE TITLE
Test that the GeoHealthCheck can talk to the cached service end-points: GetCaps, DescProc

### ISSUE THREAD

**Issue by cehbrecht** [roocs/rook#60]

**Comment by cehbrecht** [comment]
Using nginx to cache `GetCaps` and `DescribeProcess` requests:
https://github.com/bird-house/ansible-wps-playbook/blob/master/roles/pywps/templates/nginx.conf.j2

`Execute` requests are not cached.

Cache is currently valid for 10 minutes. 

Added `health/` endpoint for load-balancer checks. Redirects to `GetCaps` request.

**Comment by agstephens** [comment]
Working in production.
