### ISSUE TITLE
Handling of original file URLs

### ISSUE THREAD

**Issue by ellesmith88** [roocs/rook#74]
We need to handle the file URLs. Currently the file paths from the subset operation can be accessed from `result.file_paths` but the file URLs for the 'original files' aren't added to this list when added to the `ResultSet()` as they are not files (This is handled in `daops`). See below for current `wps_subset.py`:

https://github.com/roocs/rook/blob/a70a302ea217c14d266181bbda790886a5106d67/rook/processes/wps_subset.py#L168-L169
https://github.com/roocs/rook/blob/a70a302ea217c14d266181bbda790886a5106d67/rook/processes/wps_subset.py#L185-L189

How do we want to handle the file URLs - should the urls be added to the metalink document?

**Comment by cehbrecht** [comment]
We need a public HTTP download url for the original files which can then be added to the metalink document. Maybe the metalink result object needs to be changed to keep the download urls as they are.


We already have an nginx. We might use it for the file downloads?

**Comment by cehbrecht** [comment]
@ellesmith88 you can already set `http://` urls in the `MetaFile` object:
```
mf = MetaFile('NetCDF file', 'NetCDF file', fmt=FORMATS.NETCDF)
mf.url = 'http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r5i1p1f1/Amon/tas/gn/v20190710/tas_Amon_MPI-ESM1-2-LR_historical_r5i1p1f1_gn_185001-186912.nc'
ml4.append(mf)
```

If it is a file we use `mf.file = file` and for http urls we use `mf.url = url`. This decision needs to be in rook.

**Comment by cehbrecht** [comment]
> If it is a file we use `mf.file = file` and for http urls we use `mf.url = url`. This decision needs to be in rook.

maybe can extend `MetaFile` later with `mf.uri = uri` it delegate this decision to `MetaFile`.

**Comment by ellesmith88** [comment]
@cehbrecht Ok, so we can just check if we're getting URLs or files and use either `mf.url` or` mf.file` like this:

```
        for result in result.file_uris:
            mf = MetaFile("NetCDF file", "NetCDF file", fmt=FORMATS.NETCDF)

            if director.use_original_files:
                mf.url = result
            else:    
                mf.file = result
                
            ml4.append(mf)
```

Does this part `fmt=FORMATS.NETCDF` make any difference?

**Comment by cehbrecht** [comment]
> @cehbrecht Ok, so we can just check if we're getting URLs or files and use either `mf.url` or` mf.file` like this:
> 
> ```
>         for result in result.file_uris:
>             mf = MetaFile("NetCDF file", "NetCDF file", fmt=FORMATS.NETCDF)
> 
>             if director.use_original_files:
>                 mf.url = result
>             else:    
>                 mf.file = result
>                 
>             ml4.append(mf)
> ```

yes. looks fine.
> 
> Does this part `fmt=FORMATS.NETCDF` make any difference?

No. It is just for the metalink description.

**Comment by ellesmith88** [comment]
@cehbrecht I will add this in, thank you

**Comment by ellesmith88** [comment]
implemented
