### ISSUE TITLE
Problem with incorrect URL on ESGF Data Node

### ISSUE THREAD

**Issue by agstephens** [roocs/rook#90]
In this example the path mapping to the ESGF files is wrong:

Path provided by service: https://data.mips.copernicus-climate.eu/thredds/fileServer/esg_c3s-cmip6/CMIP6/CMIP/IPSL/IPSL-CM6A-LR/historical/r1i1p1f1/Amon/rlds/gr/v20180803/rlds_Amon_IPSL-CM6A-LR_historical_r1i1p1f1_gr_185001-201412.nc

Actual path: https://data.mips.copernicus-climate.eu/thredds/fileServer/esg_c3s-cmip6/CMIP/IPSL/IPSL-CM6A-LR/historical/r1i1p1f1/Amon/rlds/gr/v20180803/rlds_Amon_IPSL-CM6A-LR_historical_r1i1p1f1_gr_185001-201412.nc

Difference: Path provided by service has an extra "/CMIP6" in the URL

Explanation: This probably relates to our new DatasetMapper class in roocs_utils - but is likely to be fixed when all the correct versions of the repos are deployed.

Resolution: @ellesmith88 thinks we can update the `rook` code that maps the path and that should work.

**Comment by ellesmith88** [comment]
I've pushed an updated to the `c3s_mapper` branch on `rook` which will provide the correct path when compared with updated inventory

**Comment by ellesmith88** [comment]
closed by PR #97
