### ISSUE TITLE
Download URLs are wrong if no subset params are sent to rook in a workflow

### ISSUE THREAD

**Issue by agstephens** [roocs/rook#92]
Download URLs are wrong if no subset params are sent to rook in a workflow.

E.g.:

```
wf = ops.Subset(
            ops.Input(
                'rlds', ['CMIP6.CMIP.IPSL.IPSL-CM6A-LR.historical.r1i1p1f1.Amon.rlds.gr.v20180803']
        )
)
```

The workflow completes but the metalink has an invalid URL in it:

`/usr/local/src/rook/https:/data.mips.copernicus-climate.eu/thredds/fileServer/esg_c3s-cmip6/CMIP6/CMIP/IPSL/IPSL-CM6A-LR/historical/r1i1p1f1/Amon/rlds/gr/v20180803/rlds_Amon_IPSL-CM6A-LR_historical_r1i1p1f1_gr_185001-201412.nc`

**Comment by cehbrecht** [comment]
Fixed by PR #96
