### ISSUE TITLE
Discuss whether we should put the Provenance outputs in the input.meta4 XML response

### ISSUE THREAD

**Issue by agstephens** [roocs/rook#99]
At present the PROV records are in the ExecuteResponse XML.

It would be easier for ECMWF if they were in the input.meta4 response so that `rooki` could pick them up automatically when calling `download_urls()`.

@agstephens and @cehbrecht to discuss

**Comment by agstephens** [comment]
@cehbrecht Please let James know how `rooki` proposes to access the provenance info.

**Comment by cehbrecht** [comment]
@JamesVarndell the rooki client interface has currently a method to access the provenance separately:
https://nbviewer.jupyter.org/github/roocs/rooki/blob/master/notebooks/demo/demo-rooki-prov.ipynb

... using `resp.provenance()` and `resp.provenance_image()`. The current `download_urls()` method only returns the results of the operation ... only netcdf files.

How would you like to have it?
* having all outputs (netcdf + provenance) in the metalink document?
* keep the current rooki interface: `download_urls()` for netcdf only and `provenance()` separate?
* ... or `use download_urls()` but with a filter parameter for file types (netcdf, provenance, all)?

**Comment by JamesVarndell** [comment]
Hi @cehbrecht, I think the current API is fine - I just wasn't aware of the provenance methods. I'll try incorporating these into my adaptor now. Thanks!

**Comment by JamesVarndell** [comment]
Hi @cehbrecht, just a quick follow-up - I'm now retrieving the provenance information using `resp.provenance()` and `resp.provenance_image()` and zipping the files up in the catalogue request responses. It's all working well - thanks for your help!

**Comment by agstephens** [comment]
Thanks @JamesVarndell, that's great. I'll close this issue.
